### ISSUE TITLE
Examples with language filters are broken

### ISSUE THREAD

**Issue by herrstucki** [zazuko/rdf-cube-view-query#17]
When running either cube-demo-lookup.js or elcom-lookup.js, the script fails with `UnhandledPromiseRejectionWarning: TypeError: child.clone is not a function`.

Removing the language filter "solves" that.

**Comment by herrstucki** [comment]
The bug seems to have been introduced in https://github.com/zazuko/rdf-cube-view-query/commit/91da7b4e68bd495832f290398fb10ca9ffa519fe, previous commits don't have it.

**Comment by bergos** [comment]
@herrstucki that's strange. Both examples work without error on my machine. I think I had to fix a bug in the `rdf-sparql-builder` package for that change. Did you reinstall the dependencies afterwards? Looks like the changes are related to your error message: https://github.com/zazuko/rdf-sparql-builder/commit/70916db2029a1519fc0fda3a081be422d84e852b

**Comment by herrstucki** [comment]
Ah, `npm i` didn't update it to 0.1.6 because I already had a package-lock.json and the dependency was still listed as `^0.1.5`. Deleting package-lock.json and node_modules fixed it.

You might want to bump the version in package.json to `^0.1.6` and also commit the package-lock.json (as is recommended).
